apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: admin
  replicas: {{ .Values.admin.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admin
    spec:
      containers:
      - name: admin
        image: {{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}
        imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: PORT
          value: 8080
        - name: REACT_APP_OPEN_BALENA_POSTGREST_URL
          value: http://postgrest.{{ .Values.global.hostname }}:8000
        - name: REACT_APP_OPEN_BALENA_REMOTE_URL
          value: http://remote.{{ .Values.global.hostname }}:10000
        - name: REACT_APP_OPEN_BALENA_API_URL
          value: https://api.{{ .Values.global.hostname }}
        - name: REACT_APP_OPEN_BALENA_API_VERSION
          value: {{ .Values.admin.apiVersion }}
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]