apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgrest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: postgrest
  replicas: {{ .Values.postgrest.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgrest
    spec:
      containers:
      - name: postgrest
        image: {{ .Values.postgrest.image.repository }}:{{ .Values.postgrest.image.tag }}
        imagePullPolicy: {{ .Values.postgrest.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8000
        env:
        - name: PGRST_DB_URI
          value: postgres://{{ .Values.postgrest.dbUser }}:{{ .Values.postgrest.dbPassword }}@{{ .Values.postgrest.dbHost }}:{{ .Values.global.dbPort }}/resin
        - name: PGRST_JWT_SECRET
          value: {{ .Values.postgrest.jwtSecret }}
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
