apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: remote
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: remote
  replicas: {{ .Values.remote.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: remote
    spec:
      containers:
      - name: remote
        image: {{ .Values.remote.image.repository }}:{{ .Values.remote.image.tag }}
        imagePullPolicy: {{ .Values.remote.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          - name: 10000-tcp
            containerPort: 10000
          - name: 10001-tcp
            containerPort: 10001
          - name: 10002-tcp
            containerPort: 10002
          - name: 10003-tcp
            containerPort: 10003
          - name: 10004-tcp
            containerPort: 10004
          - name: 10005-tcp
            containerPort: 10005
          - name: 10006-tcp
            containerPort: 10006
          - name: 10007-tcp
            containerPort: 10007
        env:
        - name: BALENARC_BALENA_URL
          value: {{ .Values.remote.hostname }}
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
