apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openbalena-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena-admin.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.http.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    cert-manager.io/issuer: openbalena-admin-certificate-issuer
spec:
  tls:
  - hosts:
    - admin.{{ .Values.global.hostname }}
    - postgrest.{{ .Values.global.hostname }}
    - remote.{{ .Values.global.hostname }}
    secretName: {{ include "openbalena-admin.fullname" . }}-tls
  ingressClassName: openbalena-admin-haproxy
  rules:
  - host: admin.{{ .Values.global.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "openbalena-admin.fullname" . }}-ui
            port:
              number: 80
  - host: postgrest.{{ .Values.global.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "openbalena-admin.fullname" . }}-postgrest
            port:
              number: 80
  - host: remote.{{ .Values.global.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "openbalena-admin.fullname" . }}-remote
            port:
              number: 80