apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-username
  namespace: {{ .Release.Namespace }}
data:
  data: {{ .Values.secrets.dbUser }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-password
  namespace: {{ .Release.Namespace }}
data:
  data: {{ .Values.secrets.dbPassword }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-jwt_secret
  namespace: {{ .Release.Namespace }}
data:
  data: {{ .Values.secrets.jwtSecret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-access_key
  namespace: {{ .Release.Namespace }}
data:
  data: {{ .Values.secrets.s3AccessKey }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-secret_key
  namespace: {{ .Release.Namespace }}
data:
  data: {{ .Values.secrets.s3SecretKey }}