apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-username
  namespace: {{ .Release.Namespace }}
stringData:
  data: {{ .Values.secrets.dbUser }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-password
  namespace: {{ .Release.Namespace }}
stringData:
  data: {{ .Values.secrets.dbPassword }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-jwt-secret
  namespace: {{ .Release.Namespace }}
stringData:
  data: {{ .Values.secrets.jwtSecret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-access-key
  namespace: {{ .Release.Namespace }}
stringData:
  data: {{ .Values.secrets.s3AccessKey }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-secret-key
  namespace: {{ .Release.Namespace }}
stringData:
  data: {{ .Values.secrets.s3SecretKey }}