apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-db-creds
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.secrets.db.username }}
  password: {{ .Values.secrets.db.password }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-jwt-auth
  namespace: {{ .Release.Namespace }}
stringData:
  secret: {{ .Values.secrets.jwt.secret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openbalena-s3-keys
  namespace: {{ .Release.Namespace }}
stringData:
  accesskey: {{ .Values.secrets.s3.accesskey }}
  secretkey: {{ .Values.secrets.s3.secretkey }}