apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admin
spec:
  selector:
    app.kubernetes.io/component: admin
  ports:
  - port: 443
    name: http
    protocol: TCP
    targetPort: 8080