apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgrest
spec:
  selector:
    app.kubernetes.io/component: postgrest
  ports:
  - port: 443
    name: http
    protocol: TCP
    targetPort: 3000