apiVersion: v1
kind: Service
metadata:
  name: remote
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: remote
spec:
  selector:
    app.kubernetes.io/component: remote
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 10000
  - port: 443
    name: https
    protocol: TCP
    targetPort: 10000
  - port: 10001
    name: 10001-tcp
    protocol: TCP
    targetPort: 10001
  - port: 10002
    name: 10002-tcp
    protocol: TCP
    targetPort: 10002
  - port: 10003
    name: 10003-tcp
    protocol: TCP
    targetPort: 10003
  - port: 10004
    name: 10004-tcp
    protocol: TCP
    targetPort: 10004
  - port: 10005
    name: 10005-tcp
    protocol: TCP
    targetPort: 10005
  - port: 10006
    name: 10006-tcp
    protocol: TCP
    targetPort: 10006
  - port: 10007
    name: 10007-tcp
    protocol: TCP
    targetPort: 10007
  - port: 10008
    name: 10008-tcp
    protocol: TCP
    targetPort: 10008
  - port: 10009
    name: 10009-tcp
    protocol: TCP
    targetPort: 10009